version: "3.9"
services:
    php-composer:
        image: composer:latest
        volumes:
            - ./volumes/composer:/app
        command: composer update --working-dir /app
    mariadb:
        image: mariadb:latest 
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./volumes/sql:/docker-entrypoint-initdb.d
    php-cgi:
        depends_on: 
            php-composer:
                condition: service_completed_successfully
            mariadb:
                condition: service_started
        build: ./images/php-fpm
        volumes:
            - ./volumes/php:/app
            - ./volumes/composer/vendor:/vendor
            - ./configs/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./logs/php-fpm:/var/log
    entry:
        image: nginx:latest
        depends_on: 
            php-cgi:
                condition: service_started
        ports:
            - "80:80"
        volumes:
            - ./volumes/php:/app
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx:/var/log/nginx
